src/components/header/PatientHeader.jsx

**JIRA TICKET NAME**
[OEUI-208](https://issues.openmrs.org/browse/OEUI-208) PatientHeader: Remove "note" section
**Summary**
- This PR removes the "note" section from the pateintHeader

OEUI-208: Remove note section from patientHeader

---

assets/css/header.css
assets/css/patientHeader.css
src/components/header/Header.jsx
src/components/header/PatientHeader.jsx

**JIRA TICKET NAME**
[OEUI-207](https://issues.openmrs.org/browse/OEUI-207) Header: location list should be formatted
**Summary**
- This PR styles the location header
**Current look:**

OEUI-207: Extract header.css to react-components

---

assets/css/patientHeader.css

[OEUI-214](https://issues.openmrs.org/browse/OEUI-214) - Patient Header not formatting correctly

OEUI-214 :changed overflow property

---

assets/css/header.css

**JIRA TICKET NAME**
[OEUI-207](https://issues.openmrs.org/browse/OEUI-207) Header: location list should be formatted
**Summary**
- This PR styles the location header
**Current look:**

OEUI-207: Style header location

---

src/components/header/Header.jsx
src/components/header/__tests__/Header.test.jsx
src/components/header/__tests__/__snapshots__/Header.test.jsx.snap

OEUI-191: Fix context link bug

---

assets/css/toolTip.css
src/components/tooltip/ToolTip.jsx
src/components/tooltip/__tests__/ToolTip.test.jsx
src/components/tooltip/__tests__/__snapshots__/ToolTip.test.jsx.snap
src/index.js

**JIRA TICKET NAME**
[OEUI-229](https://issues.openmrs.org/browse/OEUI-218) Extract tooltip from OEUI
**Summary**
- This PR creates a reusable tootip component

OEUI-229: Create reusable tooltip component

---

package-lock.json
package.json
src/components/table/SortableTable.jsx
src/index.js

[UHM-3473](https://tickets.pih-emr.org/browse/UHM-3473)

UHM-3473 : Move SortableTable components to openmrs-react-component

---

src/components/widgets/Dropdown.jsx
src/index.js

[UHM-3474](Move Dropdown component to openmrs-react-components)

UHM-3474 : Move Dropdown component

---

src/components/form/Obs.jsx
src/components/widgets/CheckBox.js
src/components/widgets/Dropdown.jsx

UHM-3490: Add checkbox support to Obs field

---

src/features/constants/actions.js
src/features/constants/index.js
src/features/constants/reducers.js
src/features/constants/sagas.js
src/features/constants/types.js
src/index.js
src/rest/constantsRest.js

UHM-3531: Add CONSTANTS store

---

src/components/widgets/CustomDatePicker.jsx

UHM-3543: Suppress time component in CustomDatePicker

---

assets/css/patientHeader.css
src/components/header/PatientHeader.jsx

WOR:201 Make patient header responsive

---

assets/css/cardList.css
src/components/cardList/CardList.jsx
src/index.js

MLW-871: Rework queues UI

---

assets/css/headerAlt.css

WOR-200-fix: removed hambuger totally from header

---

assets/css/headerAlt.css

WOR-200: Add User menu back to headerAlt

---

assets/css/taskList.css
src/components/task/TaskList.jsx
src/components/task/TaskListItem.jsx

MLW-896: Update Task List

---

assets/css/headerAlt.css
src/components/header/HeaderAlt.jsx

WOR-215: App Header in potrait mode

---

assets/css/basicLayout.css
assets/css/cardList.css
assets/css/patientHeader.css
assets/css/taskList.css
src/components/layout/BasicLayout.jsx

MLW-860 : Hide alerts with zero count

---

assets/css/widgets.css

Reverts openmrs/openmrs-react-components#173 to move it to PWA-workflow.

Revert "IS-106: Make "IC3 Appointment" text fit display"

---

README.md
src/components/README.md

Addresses issue RAUI - 22 (https://issues.openmrs.org/projects/RAUI/issues/RAUI-22?filter=allopenissues) minor fixes in readme.

RAUI - 22 : minor fixes in readme

---

src/components/obs/ObsHistory.jsx
src/domain/obs/constants.js

Reverts openmrs/openmrs-react-components#213

Revert "IS-380: ordered obs by encounters in ObsHistory Component"

---

src/components/obs/ObsHistory.jsx
src/domain/obs/constants.js
src/features/form/__tests__/util.test.js
src/features/form/util.js

See: https://pihemr.atlassian.net/secure/RapidBoard.jspa?rapidView=75&projectKey=IS&modal=detail&selectedIssue=IS-430

IS-430: Can't edit encounters created outside of IC3 from within IC3

---

src/components/form/Obs.jsx

fyi @cioan ... this seemed to be straightforward... I added "required" to the VL Bled question and it disabled the submit button until an option was sllected

add support for validations for Obs of type ButtonGroup

---

README.md

* plus minor formatting proposals

Duplicate word on paragraph 86

---

src/features/form/__tests__/sagas.test.js
src/features/form/actions.js
src/features/form/sagas.js
src/rest/orderRest.js

Combined PR for tickets RA-40 and RA-41

RA 40/RA 41

---

src/features/form/validations.jsx

Hi @mogoodrich , Gandy and I have worked on this ticket together. Can you please review these changes? Thanks!

UHM-4062, update absolute range validations

---

src/components/form/Obs.jsx
src/features/form/__tests__/validations.test.jsx
src/features/form/validations.jsx
src/localization/translations/en.json
src/localization/translations/fr.json
src/localization/translations/ht.json

Hi @mogoodrich and @Jilouwikyky, here the allowDecimals validation function for Numeric concepts. Thank you for reviewing it.

UHM-4040, validate if Numeric concepts allow decimals

---

src/components/table/SortableTable.jsx
src/components/widgets/Dropdown.jsx

https://pihemr.atlassian.net/browse/UHM-4510

Fix i18n props for SortedTable and Dropdown

---

README.md

- Added the openMRS logo
- Made changes that explain further on usability.

RAUI-27: Improving the main README file

---

src/components/README.md

This seems wrong and took me some time to realize, may save it for someone else

Corrected wrong property name
